services:
  - type: web
    name: ai-text-summarizer-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: ai-text-summarizer-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com

databases:
  - name: ai-text-summarizer-db
    databaseName: resumidor_db
    user: resumidor_db_user